### ISSUE TITLE
Typo "craft_materia" in init.lua get_material_properties

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/castle_masonry#14]
Currently line 98 of init.lua says

burn_time = minetest.get_craft_result({method="fuel", width=1, items={ItemStack(material.craft_materia)}}).time

instead of

burn_time = minetest.get_craft_result({method="fuel", width=1, items={ItemStack(material.craft_material)}}).time

The last mention of material.craft_material seems to lack its last letter,

craft_materia

instead of

craft_materiaL

**Comment by FaceDeer** [comment]
Whoops. Good catch, I'll fix.

**Comment by Bastrabun** [comment]
:D 

Now THAT's a quick reaction! Thanks!

*impressed*

**Comment by Bastrabun** [comment]
Solved, the typo is gone. *Still impressed* 

I guess I am supposed to close the issue now?

If that guess was wrong, please reopen.
