### ISSUE TITLE
Broken stonwall crafts in mtg

### ISSUE THREAD

**Issue by Niklp09** [minetest-mods/castle_masonry#24]
Stonewalls can't be crafted anymore in mtg because `group:cobble` does not exist.
Caused by https://github.com/minetest-mods/castle_masonry/commit/c382515bcade1eea49074c4055f253fb7a95cb53 (@nonfreegithub).

To the person who fixes this issue (maybe me): Please don't introduce a new group in mtg.

CC: https://github.com/Archtec-io/bugtracker/issues/136

**Comment by nonfreegithub** [comment]
`group:cobble` is the craft material **only** if `mcl_core` exist, check init.lua line 70 and 71

when MTG, the craft material is `default:cobble` instead `group:cobble`

What Stonewalls are you referring to? What ID do that have?

**Comment by Niklp09** [comment]
> group:cobble is the craft material only if mcl_core exist, check init.lua line 70 and 71

Thats wrong, check https://github.com/minetest-mods/castle_masonry/blob/c382515bcade1eea49074c4055f253fb7a95cb53/paving.lua#L23-L24 https://github.com/minetest-mods/castle_masonry/blob/c382515bcade1eea49074c4055f253fb7a95cb53/stone_wall.lua#L43-L44

> when MTG, the craft material is default:cobble instead group:cobble

nope. what you mean is cobble for pillars.

>What Stonewalls are you referring to? What ID do that have?

`castle_masonry:stonewall` (and `castle_masonry:pavement_brick` is also broken)

**Comment by nonfreegithub** [comment]
fixed in #25
