### ISSUE TITLE
Pillars crafting recipe

### ISSUE THREAD

**Issue by bell07** [minetest-mods/castle_masonry#3]
The crafing recipes for castle:pillars_"..name.."_middle are 2x3 pattern, this one "traditionally" is used for doors. And yes, we have stone-doors in https://github.com/minetest-mods/mydoors/blob/master/my_misc_doors/unlocked.lua#L43
So the recipes overlaps. I solved it for me by changing the pillar crafting to 1x3 pattern:

```
@@ -97,11 +97,11 @@ for _, row in ipairs(pillar.types) do
 	if craft_material then
 		--Choose craft material
 		minetest.register_craft({
-			output = "castle:pillars_"..name.."_middle 4",
+			output = "castle:pillars_"..name.."_middle 2",
 			recipe = {
-				{craft_material,craft_material},
-				{craft_material,craft_material},
-				{craft_material,craft_material} },
+				{craft_material},
+				{craft_material},
+				{craft_material} },
 		})
 	end
 end
```
Please check if the recipe can be changed in upstream

**Comment by FaceDeer** [comment]
Apologies for taking four months to get to this, took a bit of a modding hiatus. :) Anyway, that seems like a reasonable recipe modification. Especially given that it's possible to enable wooden pillars. I'll make the change.
